run_gradio: True
demo_public: False

# select what dataset are you going to use. choices -- > ( xsum, ccdv/cnn_dailymail )
dataset_name_or_path: ccdv/cnn_dailymail

# select which part of split dataset going to use. choices -- > ( train, valid, test )
dataset_section: test

# How many data  are you planning to evaluate -- > an integer number
limit_dataset: 500

# Which model do you plan to use --> (facebook/opt-125m, google/flan-t5-base, google/flan-t5-large, t5-base, t5-large )

model_name_or_path: t5-large

load_fp16: False
prompt_max_length: null
max_new_tokens: 500
generation_seed: 123
use_sampling: True
n_beams: 1
sampling_temp: 0.7
use_gpu: True
seeding_scheme: simple_1
gamma: 0.25
delta: 2.0
normalizers: ''
ignore_repeated_bigrams: False
detection_z_threshold: 4.0
select_green_tokens: True
skip_model_load: False
seed_separately: True
csv_path: ./result.csv